#!/bin/bash

# postinst
#
# Copyright (C) 2014 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

openbox_rc=/etc/xdg/openbox/rc.xml
lxde_openbox_rc=/etc/xdg/openbox/LXDE/rc.xml
custom_openbox_rc=/usr/share/kano-desktop/openbox/rc.xml

lightdm_config=/etc/lightdm/lightdm.conf

chromium_master_prefs=/etc/chromium/master_preferences
custom_chromium_master_prefs=/usr/share/kano-desktop/config/chromium/master_preferences

chromium_bookmarks=/etc/chromium/initial_bookmarks.html
custom_chromium_bookmarks=/usr/share/kano-desktop/config/chromium/initial_bookmarks.html

lxde_autostart=/etc/xdg/lxsession/LXDE/autostart
custom_lxde_autostart=/usr/share/kano-desktop/config/autostart/autostart

SQUEAKDIR=/usr/share/squeak

TMP_SUDOERS_FILE=/tmp/kano-desktop_conf

case "$1" in
    configure)

        # Install squeak, but only if not present
        if [ ! -d "$SQUEAKDIR" ]; then
            SQUEAKURL=http://dev.kano.me/public/squeak.tar.gz

            rm -rf /etc/skel/squeak
            rm -rf $SQUEAKDIR

            mkdir -p $SQUEAKDIR
            wget -nv $SQUEAKURL -O tmp.tar.gz
            tar -zxvf tmp.tar.gz
            mv squeak/* $SQUEAKDIR
            rm -r squeak
            rm tmp.tar.gz
        fi

        # create the squeak link to /etc/skel
        ln -s $SQUEAKDIR /etc/skel/

        # /etc/skel/.config
        mkdir -p /etc/skel/.config
        ln -s /usr/share/kano-desktop/config/pcmanfm /etc/skel/.config/pcmanfm
        ln -s /usr/share/kano-desktop/config/libfm /etc/skel/.config/libfm
        ln -s /usr/share/kano-desktop/config/lxpanel /etc/skel/.config/lxpanel
        ln -s /usr/share/kano-desktop/config/lxterminal /etc/skel/.config/lxterminal
        ln -s /usr/share/kano-desktop/config/lxsession /etc/skel/.config/lxsession

        # ensure the user can write to lxpanel config file
        chmod -R 777 /usr/share/kano-desktop/config/lxpanel

        # /etc/skel/Legal
        ln -s /usr/share/kano-desktop/Legal /etc/skel/Legal

        # /etc/skel/.bashrc
        cp /usr/share/kano-desktop/config/profile/.bashrc /etc/skel/

        # Configure openbox
        cp $openbox_rc $openbox_rc-old
        cat $custom_openbox_rc > $openbox_rc

        cp $lxde_openbox_rc $lxde_openbox_rc-old
        cat $custom_openbox_rc > $lxde_openbox_rc

        # Configure lightdm
        # Display a list of user names when logging in
        sed -i 's/#\?\s*\(greeter-hide-users\=\).*/\1false/' "$lightdm_config"
        sed -i 's/^\s*\(user-session\=\).*/# \1default/' "$lightdm_config"
        # Switch to use the Kano Greeter
        sed -i 's/^\s*\(greeter-session\=\).*/\1kano-greeter/' "$lightdm_config"

        ln -s /usr/share/kano-desktop/kano-greeter/kano-greeter.py /usr/bin/kano-greeter

        # Remove all but our default Ligtdhm Xsession from the Greeter login dialog
        # these are displayed under the password field, in a drop down list
        dir_xsession=/usr/share/xsessions
        dir_xsession_disabled=/usr/share/xsessions/disabled
        if [ ! -d $dir_xsession_disabled ]; then
            mkdir -p $dir_xsession_disabled
        fi

        if [ -f $dir_xsession/LXDE.desktop ]; then
            mv $dir_xsession/LXDE.desktop $dir_xsession_disabled
        fi

        if [ -f $dir_xsession/openbox-gnome.desktop ]; then
            mv $dir_xsession/openbox-gnome.desktop $dir_xsession_disabled
        fi

        if [ -f $dir_xsession/openbox-kde.desktop ]; then
            mv $dir_xsession/openbox-kde.desktop $dir_xsession_disabled
        fi

        if [ -f $dir_xsession/openbox.desktop ]; then
            mv $dir_xsession/openbox.desktop $dir_xsession_disabled
        fi

        # Configure chromium
        cp $chromium_master_prefs $chromium_master_prefs-old
        cat $custom_chromium_master_prefs > $chromium_master_prefs

        cp $chromium_bookmarks $chromium_bookmarks-old
        cat $custom_chromium_bookmarks > $chromium_bookmarks

        # Set kdesk as the desktop manager
        cp $lxde_autostart $lxde_autostart-old
        cp $custom_lxde_autostart $lxde_autostart

        # allow user to switch to virtual console terminals
        # Create custom sudoers file
        echo "%sudo   ALL=(root) NOPASSWD: /bin/chvt" > $TMP_SUDOERS_FILE

        # The owner and group for the sudoers file must both be 0
        chown root:root $TMP_SUDOERS_FILE

        # The file permissions must be set to 0440
        chmod 0440 $TMP_SUDOERS_FILE

        # Move the file to the sudoers directory
        mv $TMP_SUDOERS_FILE /etc/sudoers.d/

        ;;
esac

#DEBHELPER#

exit 0
