#!/bin/bash

# postinst
#
# Copyright (C) 2013 Kano Computing Ltd.
# License:   http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

lightdm_greeter_config=/etc/lightdm/lightdm-gtk-greeter.conf
custom_lightdm_greeter_config=/usr/share/kano-desktop/lightdm/lightdm-gtk-greeter.conf

lightdm_config=/etc/lightdm/lightdm.conf

chromium_master_prefs=/etc/chromium/master_preferences
custom_chromium_master_prefs=/usr/share/kano-desktop/config/chromium/master_preferences

chromium_bookmarks=/etc/chromium/initial_bookmarks.html
custom_chromium_bookmarks=/usr/share/kano-desktop/config/chromium/initial_bookmarks.html

LXDE_AUTOSTART=/etc/xdg/lxsession/LXDE/autostart

# This is to get squeak working on the system out of the box. Can be removed if short of space on SD.
SQUEAKURL=http://ftp.squeak.org/4.3/Squeak-4.3-All-in-One.zip
SQUEAKZIP=Squeak-4.3-All-in-One.zip
SQUEAKDIR=/usr/share/squeak
mkdir $SQUEAKDIR
wget -nv $SQUEAKURL 
unzip $SQUEAKZIP
mv Squeak-4.3-All-in-One.app/Contents/Resources/* $SQUEAKDIR
ln -s /usr/share/squeak /etc/skel/
rm -r Squeak-4.3-All-in-One.app
rm Squeak-4.3-All-in-One.zip

case "$1" in
    configure)

        # Make links in /etc/skel
        ln -s /usr/share/kano-desktop/config/openbox /etc/skel/.config/openbox
        ln -s /usr/share/kano-desktop/config/pcmanfm /etc/skel/.config/pcmanfm
        ln -s /usr/share/kano-desktop/config/lxpanel /etc/skel/.config/lxpanel

        ln -s /usr/share/kano-desktop/idesk/ideskrc /etc/skel/.ideskrc
        ln -s /usr/share/kano-desktop/idesk/idesktop /etc/skel/.idesktop

        # Configure lightdm
        cp $lightdm_greeter_config $lightdm_greeter_config-old
        cat $custom_lightdm_greeter_config > $lightdm_greeter_config

        # Display a list of user names when logging in
        sed -i 's/#\?\s*\(greeter-hide-users\=\).*/\1false/' "$lightdm_config"
        sed -i 's/^\s*\(user-session\=\).*/# \1default/' "$lightdm_config"

        # Configure chromium
        cp $chromium_master_prefs $chromium_master_prefs-old
        cat $custom_chromium_master_prefs >$chromium_master_prefs

        cp $chromium_bookmarks $chromium_bookmarks-old
        cat $custom_chromium_bookmarks >$chromium_bookmarks

        # Set idesk as the desktop manager
        sudo sed -i 's/\@pcmanfm --desktop --profile LXDE/\@idesk/g' $LXDE_AUTOSTART

        # Update kanux installed fonts information for the X server
        mkfontdir /usr/share/fonts/kanux
        mkfontscale /usr/share/fonts/kanux
        fc-cache

        ;;
esac

#DEBHELPER#

exit 0
