#!/bin/bash

# preinst
#
# Copyright (C) 2014 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

if [ upgrade != "$1" ] || dpkg --compare-versions "$2" lt 1.0-61.20140508; then
    dpkg-divert --package kano-desktop --add --rename \
                --divert /etc/xdg/menus/lxde-applications.menu.orig /etc/xdg/menus/lxde-applications.menu
fi

