#!/bin/bash

# ldm-session-setup-script
#
# Copyright (C) 2014,2015 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#
#  https://wiki.ubuntu.com/LightDM
#
#  This script is called by lightm during user logon session
#  We save the current time here so we can estimate usage timings
#

# Tracking of actions, in the background saves ~ 2secs on a RPi2
su - $USER -c "kano-tracker-ctl clear &"
su - $USER -c "kano-tracker-ctl new-token &"
su - $USER -c "kano-tracker-ctl session start logon-session 0 &"

# zero means proceed with login, anything else will cancel the session
exit 0
