#!/bin/bash

# ldm-session-setup-script
#
# Copyright (C) 2014 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#
#  https://wiki.ubuntu.com/LightDM
#
#  This script is called by lightm during user logon session
#  We save the current time here so we can estimate usage timings
#
su - $USER -c "kano-tracker-ctl clear"
su - $USER -c "kano-tracker-ctl session start logon-session 0"

# zero means proceed with login, anything else will cancel the session
exit 0
