#!/bin/bash

# ldm-session-cleanup-script
#
# Copyright (C) 2014,2015 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#
#  https://wiki.ubuntu.com/LightDM
#
#  This script is called by lightm when the user logs off
#  We collect the time the users spent on this session and save it on the tracker
#

su - $USER -c "kano-tracker-ctl session end logon-session 0"
su - $USER -c "kano-tracker-ctl clear"
su - $USER -c "kano-tracker-ctl new-token"
su - $USER -c "kano-sync --upload-tracking-data --silent"

# kill old session: kills any processes still running from
# the old session.

# Annoyingly, we are not passed our session ID. For now,
# kill all sessions in 'closing' state

# List the sessions
SESSIONS=$(loginctl --no-legend --no-pager |awk '{print $1}')

for s in $SESSIONS; do
    # Kill if in closing state
    STATE=$(loginctl show-session $s -p State)
    if [ "$STATE" = "State=closing" ] ; then
       loginctl kill-session $s
    fi
done

return 0
