#
# kano-mount-trigger Makefile
#
# Copyright (C) 2015 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#
# A short program which triggers an action when sent a signal

all: kano-mount-trigger

kano-mount-trigger: kano-mount-trigger.c
	gcc kano-mount-trigger.c -o kano-mount-trigger

